" Plugins {
  if filereadable(expand("~/.vimrc.bundles"))
    source ~/.vimrc.bundles
  endif
" }

" General {
  " Leaders
  let mapleader = ","
  let maplocalleader = "\\"

  " Colors
  set background=dark
  colorscheme solarized

  " Syntax higlighting
  filetype plugin indent on
  syntax enable

  " Files, backups
  set backspace=2
  set nobackup
  set nowritebackup
  set noswapfile
  set history=500
  set ruler         " show the cursor position all the time
  set showcmd       " display incomplete commands
  set incsearch     " do incremental searching
  set hlsearch      " highlight search
  set laststatus=2  " Always display the status line
  set autowrite     " Automatically :write before running commands
  set list listchars=tab:»·,trail:·,nbsp:· " Display extra whitespace

  " Mouse
  set mouse=r
  set mousehide " Hide mouse while typing

  " Text, tab and indent
  set tabstop=2
  set shiftwidth=2
  set shiftround
  set expandtab
  set ai " Auto indent
  set si " Smart indent

  " Show column limit, soft wrap but don't add breaks
  set wrap
  set linebreak
  set nolist
  set formatoptions=l

  set textwidth=100
  set colorcolumn=+1
  set nofoldenable

  " Line numbers
  set number
  set numberwidth=5

  " :W sudo saves the file
  " (useful for handling the permission-denied error)
  command W w !sudo tee % > /dev/null

  " Persistent Undo
  if has("persistent_undo")
    silent !mkdir ~/.vim/undodir > /dev/null 2>&1
    set undodir='~/.vim/undodir/'
    set undofile
    set undolevels=1000 "maximum number of changes that can be undone
    set undoreload=10000 "maximum number lines to save for undo on a buffer reload
  endif

  " Clipboard (copy-pasta)
  if has('clipboard')
        if has('unnamedplus')  " When possible use + register for copy-paste
            set clipboard=unnamed,unnamedplus
        else         " On mac and Windows, use * register for copy-paste
            set clipboard=unnamed
        endif
    endif
" }

" Local config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
