" Plugins {
  if filereadable(expand("~/.vimrc.bundles"))
    source ~/.vimrc.bundles
  endif
" }

" General {
  let mapleader = ","

  " Syntax higlighting
  filetype plugin indent on
  syntax on

  set backspace=2
  set nobackup
  set nowritebackup
  set noswapfile
  set history=50
  set ruler         " show the cursor position all the time
  set showcmd       " display incomplete commands
  set incsearch     " do incremental searching
  set laststatus=2  " Always display the status line
  set autowrite     " Automatically :write before running commands
  set list listchars=tab:»·,trail:·,nbsp:· " Display extra whitespace

  set mouse=a " Automatically enable mouse support
  set mousehide " Hide mouse while typing

  " Softtabs, 2 spaces
  set tabstop=2
  set shiftwidth=2
  set shiftround
  set expandtab

  " Make it obvious where 80 characters is
  set textwidth=100
  set colorcolumn=+1

  " Line numbers
  set number
  set numberwidth=5

  " Persistent Undo
  if has("persistent_undo")
    silent !mkdir ~/.vim/undodir > /dev/null 2>&1
    set undofile
    set undodir='~/.vim/undodir/'
  endif
" }

" Local config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
