[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# ssh-agent
# Predictable SSH authentication socket location
# so that ssh-agent works on reattach to tmux sessions.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]; then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

# Python
export PYTHONSTARTUP="${HOME}/.pythonrc"

# antigen!!!
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-history-substring-search
    zsh-users/zsh-completions

    autojump
    brew
    dirpersist
    encode64
    gitfast
    pip
EOBUNDLES
antigen theme pygmalion
antigen apply
