# ssh-agent
# Predictable SSH authentication socket location
# so that ssh-agent works on reattach to tmux sessions.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]; then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

# Python
export PYTHONSTARTUP="${HOME}/.pythonrc"

# antigen
use_antigen=false
if [[ -a ~/.antigen/antigen.zsh ]]; then
  source ~/.antigen/antigen.zsh
  use_antigen=true
elif [[ -a /usr/share/zsh-antigen/antigen.zsh ]]; then
  source /usr/share/zsh-antigen/antigen.zsh
  use_antigen=true
fi

if $use_antigen ; then
  antigen use oh-my-zsh

  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-history-substring-search
  antigen bundle zsh-users/zsh-completions

  antigen bundle aws
  antigen bundle docker
  antigen bundle golang
  antigen bundle gitfast
  antigen bundle pip
  antigen bundle python
  antigen bundle vagrant

  antigen bundle encode64
  antigen bundle extract

  antigen theme pygmalion
  antigen apply
fi

if [[ `uname` == 'Linux' ]]
then
  eval `dircolors $HOME/.dircolors`
elif [[ `uname` == 'Darwin' ]]
then
  eval `gdircolors $HOME/.dircolors`
fi

# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# https://github.com/zsh-users/zsh-autosuggestions/issues/351
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
