# ssh-agent
# Predictable SSH authentication socket location
# so that ssh-agent works on reattach to tmux sessions.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]; then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

# Python
export PYTHONSTARTUP="${HOME}/.pythonrc"

# antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-history-substring-search
    zsh-users/zsh-completions

    aws
    brew
    docker
    golang
    gitfast
    pip
    python
    vagrant

    encode64
    extract
EOBUNDLES
antigen theme pygmalion
antigen apply

if [[ `uname` == 'Linux' ]]
then
  eval `dircolors $HOME/.dircolors`
elif [[ `uname` == 'Darwin' ]]
then
  eval `gdircolors $HOME/.dircolors`
fi

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
